// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { ReadonlyJSONValue, Row } from '@rocicorp/zero';
import { createBuilder } from '@rocicorp/zero';
import type { CustomType } from 'drizzle-zero';
import type * as drizzleSchema from '../../drizzle/schema';

const attendanceTable = {
    name: 'attendance',
    columns: {
        id: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        memberId: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'member_id'
        },
        lumaEventId: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'luma_event_id'
        },
        status: {
            type: 'string',
            optional: true,
            customType: null as unknown as CustomType<
                typeof drizzleSchema,
                'attendance',
                'status'
            >
        },
        checkedInAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'checked_in_at'
        },
        createdAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'created_at'
        }
    },
    primaryKey: ['id']
} as const;
const badgesTable = {
    name: 'badges',
    columns: {
        id: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        name: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        iconAscii: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'icon_ascii'
        },
        criteria: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        createdAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'created_at'
        }
    },
    primaryKey: ['id']
} as const;
const demoSlotsTable = {
    name: 'demoSlots',
    columns: {
        id: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        memberId: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'member_id'
        },
        eventId: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'event_id'
        },
        title: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        description: {
            type: 'string',
            optional: true,
            customType: null as unknown as string
        },
        requestedTime: {
            type: 'string',
            optional: true,
            customType: null as unknown as string,
            serverName: 'requested_time'
        },
        durationMinutes: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'duration_minutes'
        },
        status: {
            type: 'string',
            optional: true,
            customType: null as unknown as 'pending' | 'confirmed' | 'canceled'
        },
        confirmedByOrganizer: {
            type: 'boolean',
            optional: true,
            customType: null as unknown as boolean,
            serverName: 'confirmed_by_organizer'
        },
        createdAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'created_at'
        },
        updatedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'updated_at'
        }
    },
    primaryKey: ['id'],
    serverName: 'demo_slots'
} as const;
const eventsTable = {
    name: 'events',
    columns: {
        id: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        lumaEventId: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'luma_event_id'
        },
        name: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        description: {
            type: 'string',
            optional: true,
            customType: null as unknown as string
        },
        coverUrl: {
            type: 'string',
            optional: true,
            customType: null as unknown as string,
            serverName: 'cover_url'
        },
        url: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        startAt: {
            type: 'number',
            optional: false,
            customType: null as unknown as number,
            serverName: 'start_at'
        },
        endAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'end_at'
        },
        timezone: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        location: {
            type: 'json',
            optional: true,
            customType: null as unknown as {
                type: string;
                name: string | null;
                address: string | null;
                lat: number | null;
                lng: number | null;
            }
        },
        stats: {
            type: 'json',
            optional: true,
            customType: null as unknown as {
                registered: number;
                checkedIn: number;
            }
        },
        isCanceled: {
            type: 'boolean',
            optional: true,
            customType: null as unknown as boolean,
            serverName: 'is_canceled'
        },
        lastSyncedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'last_synced_at'
        },
        createdAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'created_at'
        },
        updatedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'updated_at'
        }
    },
    primaryKey: ['id']
} as const;
const lumaWebhooksTable = {
    name: 'lumaWebhooks',
    columns: {
        id: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        type: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        payload: {
            type: 'json',
            optional: false,
            customType: null as unknown as ReadonlyJSONValue
        },
        signature: {
            type: 'string',
            optional: true,
            customType: null as unknown as string
        },
        receivedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'received_at'
        }
    },
    primaryKey: ['id'],
    serverName: 'luma_webhooks'
} as const;
const memberBadgesTable = {
    name: 'memberBadges',
    columns: {
        memberId: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'member_id'
        },
        badgeId: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'badge_id'
        },
        awardedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'awarded_at'
        }
    },
    primaryKey: ['memberId', 'badgeId'],
    serverName: 'member_badges'
} as const;
const pendingUsersTable = {
    name: 'pendingUsers',
    columns: {
        id: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        email: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        name: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        lumaAttendeeId: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'luma_attendee_id'
        },
        subscribedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'subscribed_at'
        },
        approvedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'approved_at'
        },
        createdAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'created_at'
        },
        updatedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'updated_at'
        }
    },
    primaryKey: ['id'],
    serverName: 'pending_users'
} as const;
const profilesTable = {
    name: 'profiles',
    columns: {
        id: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        clerkUserId: {
            type: 'string',
            optional: true,
            customType: null as unknown as string,
            serverName: 'clerk_user_id'
        },
        lumaEmail: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'luma_email'
        },
        verificationStatus: {
            type: 'string',
            optional: true,
            customType: null as unknown as 'pending' | 'verified',
            serverName: 'verification_status'
        },
        isAppAdmin: {
            type: 'boolean',
            optional: true,
            customType: null as unknown as boolean,
            serverName: 'is_app_admin'
        },
        lumaAttendeeId: {
            type: 'string',
            optional: true,
            customType: null as unknown as string,
            serverName: 'luma_attendee_id'
        },
        bio: {
            type: 'string',
            optional: true,
            customType: null as unknown as string
        },
        skills: {
            type: 'json',
            optional: true,
            customType: null as unknown as string[]
        },
        githubUsername: {
            type: 'string',
            optional: true,
            customType: null as unknown as string,
            serverName: 'github_username'
        },
        twitterHandle: {
            type: 'string',
            optional: true,
            customType: null as unknown as string,
            serverName: 'twitter_handle'
        },
        websiteUrl: {
            type: 'string',
            optional: true,
            customType: null as unknown as string,
            serverName: 'website_url'
        },
        role: {
            type: 'string',
            optional: true,
            customType: null as unknown as string
        },
        seekingFunding: {
            type: 'boolean',
            optional: true,
            customType: null as unknown as boolean,
            serverName: 'seeking_funding'
        },
        openToMentoring: {
            type: 'boolean',
            optional: true,
            customType: null as unknown as boolean,
            serverName: 'open_to_mentoring'
        },
        streakCount: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'streak_count'
        },
        onboardingDismissed: {
            type: 'boolean',
            optional: true,
            customType: null as unknown as boolean,
            serverName: 'onboarding_dismissed'
        },
        createdAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'created_at'
        },
        updatedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'updated_at'
        }
    },
    primaryKey: ['id']
} as const;
const projectsTable = {
    name: 'projects',
    columns: {
        id: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        memberId: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'member_id'
        },
        title: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        description: {
            type: 'string',
            optional: true,
            customType: null as unknown as string
        },
        tags: {
            type: 'json',
            optional: true,
            customType: null as unknown as string[]
        },
        imageUrls: {
            type: 'json',
            optional: true,
            customType: null as unknown as string[],
            serverName: 'image_urls'
        },
        githubUrl: {
            type: 'string',
            optional: true,
            customType: null as unknown as string,
            serverName: 'github_url'
        },
        publicUrl: {
            type: 'string',
            optional: true,
            customType: null as unknown as string,
            serverName: 'public_url'
        },
        createdAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'created_at'
        },
        updatedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'updated_at'
        }
    },
    primaryKey: ['id']
} as const;
const surveyResponsesTable = {
    name: 'surveyResponses',
    columns: {
        id: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        surveyId: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'survey_id'
        },
        memberId: {
            type: 'string',
            optional: false,
            customType: null as unknown as string,
            serverName: 'member_id'
        },
        responses: {
            type: 'json',
            optional: true,
            customType: null as unknown as CustomType<
                typeof drizzleSchema,
                'surveyResponses',
                'responses'
            >
        },
        isComplete: {
            type: 'boolean',
            optional: true,
            customType: null as unknown as boolean,
            serverName: 'is_complete'
        },
        submittedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'submitted_at'
        },
        createdAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'created_at'
        },
        updatedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'updated_at'
        }
    },
    primaryKey: ['id'],
    serverName: 'survey_responses'
} as const;
const surveysTable = {
    name: 'surveys',
    columns: {
        id: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        slug: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        title: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        description: {
            type: 'string',
            optional: false,
            customType: null as unknown as string
        },
        type: {
            type: 'string',
            optional: false,
            customType: null as unknown as 'onboarding' | 'annual' | 'event'
        },
        isActive: {
            type: 'boolean',
            optional: true,
            customType: null as unknown as boolean,
            serverName: 'is_active'
        },
        questions: {
            type: 'json',
            optional: false,
            customType: null as unknown as CustomType<
                typeof drizzleSchema,
                'surveys',
                'questions'
            >
        },
        createdAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'created_at'
        },
        updatedAt: {
            type: 'number',
            optional: true,
            customType: null as unknown as number,
            serverName: 'updated_at'
        }
    },
    primaryKey: ['id']
} as const;
const attendanceRelationships = {
    member: [
        {
            sourceField: ['memberId'],
            destField: ['id'],
            destSchema: 'profiles',
            cardinality: 'one'
        }
    ]
} as const;
const badgesRelationships = {
    memberBadges: [
        {
            sourceField: ['id'],
            destField: ['badgeId'],
            destSchema: 'memberBadges',
            cardinality: 'many'
        }
    ]
} as const;
const demoSlotsRelationships = {
    member: [
        {
            sourceField: ['memberId'],
            destField: ['id'],
            destSchema: 'profiles',
            cardinality: 'one'
        }
    ],
    event: [
        {
            sourceField: ['eventId'],
            destField: ['id'],
            destSchema: 'events',
            cardinality: 'one'
        }
    ]
} as const;
const eventsRelationships = {
    demoSlots: [
        {
            sourceField: ['id'],
            destField: ['eventId'],
            destSchema: 'demoSlots',
            cardinality: 'many'
        }
    ]
} as const;
const memberBadgesRelationships = {
    member: [
        {
            sourceField: ['memberId'],
            destField: ['id'],
            destSchema: 'profiles',
            cardinality: 'one'
        }
    ],
    badge: [
        {
            sourceField: ['badgeId'],
            destField: ['id'],
            destSchema: 'badges',
            cardinality: 'one'
        }
    ]
} as const;
const profilesRelationships = {
    projects: [
        {
            sourceField: ['id'],
            destField: ['memberId'],
            destSchema: 'projects',
            cardinality: 'many'
        }
    ],
    memberBadges: [
        {
            sourceField: ['id'],
            destField: ['memberId'],
            destSchema: 'memberBadges',
            cardinality: 'many'
        }
    ],
    attendance: [
        {
            sourceField: ['id'],
            destField: ['memberId'],
            destSchema: 'attendance',
            cardinality: 'many'
        }
    ],
    surveyResponses: [
        {
            sourceField: ['id'],
            destField: ['memberId'],
            destSchema: 'surveyResponses',
            cardinality: 'many'
        }
    ],
    demoSlots: [
        {
            sourceField: ['id'],
            destField: ['memberId'],
            destSchema: 'demoSlots',
            cardinality: 'many'
        }
    ]
} as const;
const projectsRelationships = {
    member: [
        {
            sourceField: ['memberId'],
            destField: ['id'],
            destSchema: 'profiles',
            cardinality: 'one'
        }
    ]
} as const;
const surveyResponsesRelationships = {
    survey: [
        {
            sourceField: ['surveyId'],
            destField: ['id'],
            destSchema: 'surveys',
            cardinality: 'one'
        }
    ],
    member: [
        {
            sourceField: ['memberId'],
            destField: ['id'],
            destSchema: 'profiles',
            cardinality: 'one'
        }
    ]
} as const;
const surveysRelationships = {
    responses: [
        {
            sourceField: ['id'],
            destField: ['surveyId'],
            destSchema: 'surveyResponses',
            cardinality: 'many'
        }
    ]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    tables: {
        attendance: attendanceTable,
        badges: badgesTable,
        demoSlots: demoSlotsTable,
        events: eventsTable,
        lumaWebhooks: lumaWebhooksTable,
        memberBadges: memberBadgesTable,
        pendingUsers: pendingUsersTable,
        profiles: profilesTable,
        projects: projectsTable,
        surveyResponses: surveyResponsesTable,
        surveys: surveysTable
    },
    relationships: {
        attendance: attendanceRelationships,
        badges: badgesRelationships,
        demoSlots: demoSlotsRelationships,
        events: eventsRelationships,
        memberBadges: memberBadgesRelationships,
        profiles: profilesRelationships,
        projects: projectsRelationships,
        surveyResponses: surveyResponsesRelationships,
        surveys: surveysRelationships
    },
    enableLegacyQueries: false,
    enableLegacyMutators: false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "attendance" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Attendance = Row<(typeof schema)['tables']['attendance']>;
/**
 * Represents a row from the "badges" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Badge = Row<(typeof schema)['tables']['badges']>;
/**
 * Represents a row from the "demoSlots" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type DemoSlot = Row<(typeof schema)['tables']['demoSlots']>;
/**
 * Represents a row from the "events" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Event = Row<(typeof schema)['tables']['events']>;
/**
 * Represents a row from the "lumaWebhooks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type LumaWebhook = Row<(typeof schema)['tables']['lumaWebhooks']>;
/**
 * Represents a row from the "memberBadges" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type MemberBadge = Row<(typeof schema)['tables']['memberBadges']>;
/**
 * Represents a row from the "pendingUsers" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PendingUser = Row<(typeof schema)['tables']['pendingUsers']>;
/**
 * Represents a row from the "profiles" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Profile = Row<(typeof schema)['tables']['profiles']>;
/**
 * Represents a row from the "projects" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Project = Row<(typeof schema)['tables']['projects']>;
/**
 * Represents a row from the "surveyResponses" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SurveyResponse = Row<(typeof schema)['tables']['surveyResponses']>;
/**
 * Represents a row from the "surveys" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Survey = Row<(typeof schema)['tables']['surveys']>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
    interface DefaultTypes {
        schema: Schema;
    }
}
